name: diabete_app1
description: A Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  health: 13.3.1
  permission_handler: ^11.0.0
  pedometer: ^4.2.0
  percent_indicator: ^4.2.3
  firebase_core: ^3.15.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.6.12

  fl_chart: ^0.69.2
  intl: 0.20.2
  google_fonts: ^6.3.3
  google_nav_bar: ^5.0.7

  shared_preferences: ^2.5.5
  http: ^1.6.0
  image_picker: ^1.2.2
  table_calendar: 3.2.0

  flutter_local_notifications: ^17.2.4
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/boissons/
    - assets/images/breakfast/
    - assets/images/dinner/
    - assets/images/dessert/
    - assets/images/snacks/
    - assets/images/healthy/
    - assets/images/poisson/
    - assets/images/salade/
    - assets/images/soupe/
    - assets/images/viande/
    - assets/typeRepas/