name: diabete_app1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  firebase_core: ^3.15.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.6.12

  # ── Module Nutrition (nouveau)
  http: ^1.2.2                  # Appels API OpenFoodFacts
  mobile_scanner: ^6.0.0        # Scanner code-barres

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/